export const SET_SHOW_LOADING = 'SET_SHOW_LOADING';
export const SET_SHOW_OVERLAY = 'SET_SHOW_OVERLAY';
export const SET_SHOW_UPLOADING = 'SET_SHOW_UPLOADING';
export const SET_SHOW_UPLOADED = 'SET_SHOW_UPLOADED';

// JOB DETAILS ACTIONS
export const SET_JOB_DETAILS = 'SET_JOB_DETAILS';
export const SET_SHOW_LOADING_TOGGLE = 'SET_SHOW_LOADING_TOGGLE';

// TRACKER ACTIONS
export const SET_TRACKER_BOOKING = 'SET_TRACKER_BOOKING';
export const SET_TRACKER_DAILYNOTE = 'SET_TRACKER_DAILYNOTE';
