export default {
  container: {
    // flex: 1,
    borderRadius: 5,
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: "#FAF9FE",
    paddingBottom: 10,
  },
  textStyle: {
    color: "#FFFFFF",
  },
  contentContainer: {
    backgroundColor: "#2E9298",
    borderRadius: 10,
    padding: 10,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowRadius: 5,
    shadowOpacity: 1.0,
  },
  dailyNoteItemContainer: {
    height: 50,
    backgroundColor: "#FAF9FE",
    marginTop: 5,
  },
  dailyNoteLabel: {
    width: 100,
    justifyContent: "center",
    paddingLeft: 10,
  },
  dailyNoteClock: {
    backgroundColor: "white",
    flexDirection: "column",
    borderTopLeftRadius: 7,
    borderBottomLeftRadius: 7,
    borderWidth: 0.5,
    borderColor: "#EAEAEA",
    borderRight: 0,
  },
  dailyNoteTime: {
    marginLeft: 10,
    flex: 1,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  dailyNoteClockIcon: {
    width: 100,
    height: 50,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
  },
  textAreaContainer: {
    borderColor: "#EAEAEA",
    borderWidth: 0.5,
    padding: 5,
    borderTopLeftRadius: 7,
    borderBottomLeftRadius: 7,
    borderRightWidth: 0,
    flex: 1,
  },
  textArea: {
    justifyContent: "flex-start",
  },
};
